AllCops:
  DisabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - "hacking/**/*"
    - "vendor/**/*"
    - "data/**/*"
    - "bin/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
